# Generated by Django 4.2.7 on 2023-11-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ìs_published',
            new_name='is_published',
        ),
    ]
